// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Redis.Context;

namespace Redis.Migrations
{
    [DbContext(typeof(RedisContext))]
    [Migration("20210823150321_baseMigration")]
    partial class baseMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Redis.Models.Igra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("KorisnikIgraId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.Property<string>("Zanr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikIgraId");

                    b.ToTable("Igras");
                });

            modelBuilder.Entity("Redis.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("KorisnikIgraId")
                        .HasColumnType("int");

                    b.Property<string>("Lozinka")
                        .HasColumnType("text");

                    b.Property<string>("Uloga")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikIgraId");

                    b.ToTable("Korisniks");
                });

            modelBuilder.Entity("Redis.Models.KorisnikIgra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdIgra")
                        .HasColumnType("int");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KorisnikIgras");
                });

            modelBuilder.Entity("Redis.Models.Igra", b =>
                {
                    b.HasOne("Redis.Models.KorisnikIgra", null)
                        .WithMany("Igras")
                        .HasForeignKey("KorisnikIgraId");
                });

            modelBuilder.Entity("Redis.Models.Korisnik", b =>
                {
                    b.HasOne("Redis.Models.KorisnikIgra", null)
                        .WithMany("Korisniks")
                        .HasForeignKey("KorisnikIgraId");
                });

            modelBuilder.Entity("Redis.Models.KorisnikIgra", b =>
                {
                    b.Navigation("Igras");

                    b.Navigation("Korisniks");
                });
#pragma warning restore 612, 618
        }
    }
}
